jQuery(function($){$(window).on('scroll',function(){if($(window).scrollTop()>250000){$('.header').addClass('sticky fade_down_effect');}else{$('.header').removeClass('sticky fade_down_effect');}});if($(window).width()<991){$(".navbar-nav li a").on("click",function(){$(this).parent("li").find(".dropdown-menu").slideToggle();$(this).find("i").toggleClass("fa-angle-up fa-angle-down");});}
    if($('.countdown').length>0){$(".countdown").jCounter({date:'18 December 2019 08:30:00',fallback:function(){console.log("count finished!")}});}
    var skl=true;$('.ts-funfact').appear();$('.ts-funfact').on('appear',function(){if(skl){$('.counterUp').each(function(){var $this=$(this);jQuery({Counter:0}).animate({Counter:$this.attr('data-counter')},{duration:8000,easing:'swing',step:function(){var num=Math.ceil(this.Counter).toString();if(Number(num)>99999){while(/(\d+)(\d{3})/.test(num)){num=num.replace(/(\d+)(\d{3})/,'');}}
            $this.html(num);}});});skl=false;}});if($('.grid').length>0){var $portfolioGrid=$('.grid'),colWidth=function(){var w=$portfolioGrid.width(),columnNum=1,columnWidth=0;if(w>1200){columnNum=3;}else if(w>900){columnNum=3;}else if(w>600){columnNum=2;}else if(w>450){columnNum=2;}else if(w>385){columnNum=1;}
        columnWidth=Math.floor(w/columnNum);$portfolioGrid.find('.grid-item').each(function(){var $item=$(this),multiplier_w=$item.attr('class').match(/grid-item-w(\d)/),multiplier_h=$item.attr('class').match(/grid-item-h(\d)/),width=multiplier_w?columnWidth*multiplier_w[1]:columnWidth,height=multiplier_h?columnWidth*multiplier_h[1]*0.4-12:columnWidth*0.3;$item.css({width:width,});});return columnWidth;},isotope=function(){$portfolioGrid.isotope({resizable:true,itemSelector:'.grid-item',masonry:{columnWidth:colWidth(),gutterWidth:3}});};isotope();$(window).resize(isotope);}
    if($('.main-slider').length>0){var bannerSlider=$(".main-slider");bannerSlider.owlCarousel({items:1,mouseDrag:false,loop:false,touchDrag:false,autoplay:false,dots:false,autoplayTimeout:5000,animateOut:'fadeOut',autoplayHoverPause:true,smartSpeed:250,});}
    $('.ts-image-popup').magnificPopup({type:'inline',closeOnContentClick:false,midClick:true,preloader:false,callbacks:{beforeOpen:function(){this.st.mainClass=this.st.el.attr('data-effect');}},zoom:{enabled:true,duration:500,},mainClass:'mfp-fade',});$('.ts-popup').magnificPopup({type:'image',closeOnContentClick:false,midClick:true,callbacks:{beforeOpen:function(){this.st.mainClass=this.st.el.attr('data-effect');}},zoom:{enabled:true,duration:500,},mainClass:'mfp-fade',});$('.ts-video-popup').magnificPopup({type:'iframe',closeOnContentClick:false,midClick:true,callbacks:{beforeOpen:function(){this.st.mainClass=this.st.el.attr('data-effect');}},zoom:{enabled:true,duration:500,},mainClass:'mfp-fade',});$('.tile').on('mouseover',function(){$(this).children('.photo').css({'transform':'scale('+$(this).attr('data-scale')+')'});}).on('mouseout',function(){$(this).children('.photo').css({'transform':'scale(1)'});}).on('mousemove',function(e){$(this).children('.photo').css({'transform-origin':((e.pageX-$(this).offset().left)/$(this).width())*100+'% '+((e.pageY-$(this).offset().top)/$(this).height())*100+'%'});}).each(function(){$(this).append('<div class="photo"></div>').children('.photo').css({'background-image':'url('+$(this).attr('data-image')+')'});});var wow=new WOW({animateClass:'animated',mobile:false});wow.init();$(window).on('scroll',function(){if($(window).scrollTop()>$(window).height()){$(".BackTo").fadeIn('slow');}else{$(".BackTo").fadeOut('slow');}});$("body, html").on("click",".BackTo",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#kayit-formu').offset().top},800);});$("body, html").on("click",".kayit-formu",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#kayit-formu').offset().top},800);});$("body, html").on("click",".workshop",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#workshop').offset().top},800);});$("body, html").on("click",".program",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#program').offset().top},800);});$("body, html").on("click",".hakkinda",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#hakkinda').offset().top},800);});$("body, html").on("click",".iletisim",function(e){e.preventDefault();$('html, body').animate({scrollTop:$('#iletisim').offset().top},800);});});function mailKontrol(email){var re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(String(email).toLowerCase());}
function form_gonder()
{var query=$('#contact-form').serialize();var header=" LÃ¼tfen Bilgilerinizi Eksiksiz Doldurunuz. <br/>";var message="";var gsm_check=$('#gsm').val();var gsmLength=gsm_check.length;var email=$('#email').val();if($('#adsoyad').val()==""){message=message+"* Ad Soyad giriniz.<br/>";$('#adsoyad').focus();}
    if($('#unvan').val()==""){message=message+"* Unvan giriniz.<br/>";$('#unvan').focus();}
    if($('#firma_adi').val()==""){message=message+"* Firma adÄ± giriniz.<br/>";$('#firma_adi').focus();}
    if($('#gsm').val()==""){message=message+"* Cep telefonu numarasÄ± giriniz.<br/>";$('#gsm').focus();}else if(gsmLength<11){message=message+"* Cep telefonu numarasÄ± eksiksiz giriniz.<br/>";$('#gsm').focus();}
    if($('#email').val()==""){message=message+"* E-mail adresi giriniz.<br/>";$('#email').focus();}else if(!mailKontrol(email)){message=message+"* LÃ¼tfen geÃ§erli bir E-mail adresi giriniz.<br/>";$('#email').focus();}
    var workshop1=document.getElementsByName('workshop_1');var workshopSec1="";for(i=0;i<workshop1.length;i++){if(workshop1[i].checked)
    workshopSec1=workshop1[i].value;}
    if(workshopSec1==""){message=message+"* KatÄ±lÄ±mcÄ± iÃ§in 09:00 - 09:45 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
    var workshop2=document.getElementsByName('workshop_2');var workshopSec2="";for(i=0;i<workshop2.length;i++){if(workshop2[i].checked)
    workshopSec2=workshop2[i].value;}
    if(workshopSec2==""){message=message+"* KatÄ±lÄ±mcÄ± iÃ§in 12:00 - 12:45 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
    var workshop3=document.getElementsByName('workshop_3');var workshopSec3="";for(i=0;i<workshop3.length;i++){if(workshop3[i].checked)
    workshopSec3=workshop3[i].value;}
    if(workshopSec3==""){message=message+"* KatÄ±lÄ±mcÄ± iÃ§in 15:45 - 16:30 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
    var alumnisValue=document.getElementsByName('alumni');for(i=0;i<alumnisValue.length;i++){if(alumnisValue[i].checked)
    var alumnisValueResult=alumnisValue[i].value;}
    if(alumnisValueResult!=1&&alumnisValueResult!=2){message=message+"* KatÄ±lÄ±mcÄ± iÃ§in eski PwC Ã§alÄ±ÅŸan seÃ§eneÄŸini belirtiniz.<br/>";}else if(alumnisValueResult==1){if($('#alumni_yil').val()==""){message=message+"* KatÄ±lÄ±mcÄ± iÃ§in PwC'den ayrÄ±lma yÄ±lÄ±nÄ± giriniz.<br/>";$('#alumni_yil').focus();}}
    if($('#adet').val()>1){var toplam_katilim=$('#adet').val();for(katilim_dongu=2;katilim_dongu<=toplam_katilim;katilim_dongu++){var gsm_check=$('#gsm_'+katilim_dongu).val();var gsmLength=gsm_check.length;var email=$('#email_'+katilim_dongu).val();if($('#adsoyad_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± Ad Soyad giriniz.<br/>";}
        if($('#unvan_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± Unvan giriniz.<br/>";}
        if($('#firma_adi_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". Firma adÄ± giriniz.<br/>";}
        if($('#gsm_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± Cep telefonu numarasÄ± giriniz.<br/>";}else if(gsmLength<11){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± Cep telefonu numarasÄ± eksiksiz giriniz.<br/>";}
        if($('#email_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± E-mail adresi giriniz.<br/>";}else if(!mailKontrol(email)){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in geÃ§erli bir E-mail adresi giriniz.<br/>";}
        var workshop1=document.getElementsByClassName('workshop_1_'+katilim_dongu);var workshopSec1="";for(i=0;i<workshop1.length;i++){if(workshop1[i].checked)
            workshopSec1=workshop1[i].value;}
        if(workshopSec1==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in 09:00 - 09:45 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
        var workshop2=document.getElementsByClassName('workshop_2_'+katilim_dongu);var workshopSec2="";for(i=0;i<workshop2.length;i++){if(workshop2[i].checked)
            workshopSec2=workshop2[i].value;}
        if(workshopSec2==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in 12:00 - 12:45 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
        var workshop3=document.getElementsByClassName('workshop_3_'+katilim_dongu);var workshopSec3="";for(i=0;i<workshop3.length;i++){if(workshop3[i].checked)
            workshopSec3=workshop3[i].value;}
        if(workshopSec3==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in 15:45 - 16:30 workshop seÃ§imi yapÄ±nÄ±z.<br/>";}
        var alumnisValue=document.getElementsByClassName('katilimci_alumni_'+katilim_dongu);var alumnisValueResult="";for(i=0;i<alumnisValue.length;i++){if(alumnisValue[i].checked)
            alumnisValueResult=alumnisValue[i].value;}
        if(alumnisValueResult!=1&&alumnisValueResult!=2){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in eski PwC Ã§alÄ±ÅŸan seÃ§eneÄŸini belirtiniz.<br/>";}else if(alumnisValueResult==1){if($('#katilimci_alumni_yil_'+katilim_dongu).val()==""){message=message+"* "+katilim_dongu+". KatÄ±lÄ±mcÄ± iÃ§in PwC'den ayrÄ±lma yÄ±lÄ±nÄ± giriniz.<br/>";}}}}
    var faturaValue=document.getElementsByName('fatura-turu');for(i=0;i<faturaValue.length;i++){if(faturaValue[i].checked)
    var radioValue=faturaValue[i].value;}
    if(radioValue==1){var tc_check=$('#tc_no').val();var tcLength=tc_check.length;if($('#fatura_adsoyad').val()==""){message=message+"* Fatura adÄ± giriniz.<br/>";$('#fatura_adsoyad').focus();}
        if($('#tc_no').val()==""){message=message+"* T.C. kimlik numarasÄ± giriniz.<br/>";$('#tc_no').focus();}else if(tcLength<11){message=message+"* T.C. kimlik numarasÄ±nÄ± eksiksiz giriniz.<br/>";$('#tc_no').focus();}}else{var vergi_check=$('#vergi_no').val();var vergiLength=vergi_check.length;if($('#firma_unvani').val()==""){message=message+"* Fatura firma Ã¼nvanÄ± giriniz.<br/>";$('#firma_unvani').focus();}
        if($('#vergi_dairesi').val()==""){message=message+"* Vergi dairesi giriniz.<br/>";$('#vergi_dairesi').focus();}
        if($('#vergi_no').val()==""){message=message+"* Vergi numarasÄ± giriniz.<br/>";$('#vergi_no').focus();}else if(vergiLength<10){message=message+"* Vergi numarasÄ±nÄ± eksiksiz giriniz.<br/>";$('#vergi_no').focus();}}
    if($('#adres').val()==""){message=message+"* Fatura adresi giriniz.<br/>";$('#adres').focus();}
    if(message!=""){$('.formMessage').html("<div class=\"alert alert-warning\"><strong>UyarÄ±!</strong>"+header+message+"</div>");$("html, body").animate({scrollTop:$('#kayit-formu').offset().top},800);}else{$.ajax({type:'POST',url:'dosyalar/dahili/form_send.php',data:query,success:function(cevap)
        {$('.formMessage').html(cevap);}}).done(function(){$("html, body").animate({scrollTop:$('#kayit-formu').offset().top},800);});}}
function workshop(id)
{$.ajax({type:'POST',url:'https://www.okul.pwc.com.tr/platform/dosyalar/dahili/workshop_popup.php?v=210223',data:'id='+id,headers:{'Cache-Control':'no-cache, no-store, must-revalidate','Pragma':'no-cache','Expires':'0'},cache:false,success:function(cevap)
    {$('#popup_workshop').html(cevap);}});}
function deletePopup()
{var contentToRemove=document.querySelectorAll("#popup_workshop");$(contentToRemove).remove();}
$(document).ready(function(){$('#adet').val(1);var alumnisValue=document.getElementsByName('alumnis');for(i=0;i<alumnisValue.length;i++){if(alumnisValue[i].checked)
    var alumnisValueResult=alumnisValue[i].value;}
    if(alumnisValueResult==1){$("#ayrilma").css("display","block");}else{$("#ayrilma").css("display","none");}
    var faturaValue=document.getElementsByName('fatura-turu');for(i=0;i<faturaValue.length;i++){if(faturaValue[i].checked)
        var faturaValueResult=faturaValue[i].value;}
    if(faturaValueResult==1){$("#bireysel").css("display","block");$("#kurumsal").css("display","none");}else{$("#bireysel").css("display","none");$("#kurumsal").css("display","block");}
    $('[data-toggle="tooltip"]').tooltip();$('.adetsec').each(function(i){$(this).find('.minus').click(function(){var $input=$(this).parent().find('input');var count=parseInt($input.val())-1;count=count<1?1:count;$input.val(count);$input.change();return false;});$(this).find('.plus').click(function(){var $input=$(this).parent().find('input');var count=parseInt($input.val())+1;count=count>15?15:count;$input.val(count);$input.change();return false;});});$("input.adet").change(function(){$('span.plus').addClass('disabled');$('span.minus').addClass('disabled');var adet=$(this).val();var satir=$(' .katilimci_satir').length;$('.katilimci_satir:first-child').nextAll().remove();if(adet>1){$.get("dosyalar/dahili/katilimci.php?katilimci="+adet,function(data){$('.katilimci_satirlari').append(data);}).done(function(){setTimeout(function()
    {$('span.plus').removeClass('disabled');$('span.minus').removeClass('disabled');},1000);});}});});